version: '3.9'

services:
  drupal:
    image: drupal:10
    ports:
      - '8080:80'
    volumes:
      - ./drupal:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.6
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
